### ISSUE TITLE
Problem when parsing parameters file

### ISSUE THREAD

**Issue by kantale** [DKMS/Hapl-o-Mat#10]
There is an issue when parsing parameters file:

This is ok
```
FILENAME_INPUT=test.txt
```
But this is not!
```
FILENAME_INPUT=test.txt   
```
The difference is that there are some extra spaces at the end of the line

**Comment by sauter** [comment]
Ok, we'll have look into that.

**Comment by usolloch** [comment]
We have addressed this issue with the last update (Update for EFI2021). Hapl-o-Mat now ignores trailing space characters.
