### ISSUE TITLE
running just one allele

### ISSUE THREAD

**Issue by mbraakman** [DKMS/Hapl-o-Mat#13]
Hi, I've been using Haplomat for a while, but i get an error now i haven't gotten before.

I tried to run Haplomat for just DQB1 data, if I run g resolution or 4d it works.
When selecting P or G I get a _'segmentation fault (core dumped)'_

any suggestions?

	 _Hapl-o-Mat
	 Copyright (C) 2016 DKMS gGmbH

#########Initialization
	 MA format
#########Parameters I/O
	 Input: Matchispopulation/DQA-DQB114042022.dat
	 Output haplotypes: run/haplotypes.dat
	 Output genotypes: run/genotypes.dat
	 Output estimated haplotype frequencies: run/hfs.dat
	 Output epsilon and log(L): run/epsilon.dat
#########Parameters resolving genotypes
	 Minimal frequency of genotypes: 1e-05
	 Loci with target allele resolutions: 
	 DQB1 : G
	 Apply ambiguity filter: no
#########Parameters EM algorithm
	 Haplotype frequency initialization: perturbation
	 Epsilon: 1e-06
	 Cut haplotype frequencies: 1e-06
	 Renormalize haplotype frequencies 
	 Zero: 1e-14
	 Seed: 1000

#########Data preprocessing
Segmentation fault (core dumped)_

**Comment by mbraakman** [comment]
I now get it with multiple alleles as wel

**Comment by usolloch** [comment]
Hi,
we have also seen this error message sporadically. Usually this indicates a problem in the input file.
For example if data for one of the input loci is missing in one of the input lines. Also a blank instead of a tab separator in the input file may be the cause.
If you wish, you can send us a short input file example that leads to the "segmentation fault" error message and we will try to locate the  problem.

**Comment by mbraakman** [comment]
sorry for not responding, the problem seems to have solved it's self...

I do have another question, how would i create a HF file for DRB1-DRB345

my file contains NNNN or an allele, but the NNNN is not accepted.
i then tried to replace the NNNN by [Blank] but this also doesn't work.

any suggestions?

**Comment by usolloch** [comment]
It is possible to create haplotype frequencies for data including DRB345, but you have to minimally manipulate the input files Hapl-o-Mat uses for calculations:

The folder "data" contains a file "AllAllelesExpanded.txt".  You have to extend this file by three lines that define the "NNNN" entries.

Try to add just the three lines:

DRB3*NNNN DRB3*NNNN
DRB4*NNNN DRB4*NNNN
DRB5*NNNN DRB5*NNNN

(separated by tab!).
These lines tell the Hapl-o-Mat that NNNN-data is valid in these three loci and may only be translated into itself.

Good luck!

**Comment by mbraakman** [comment]
Great thank you!!!

Regards, Martijn

Martijn Braakman
Search Consultant / Immunogenetic consultant
Transplant Center Services
Direct phone
: +31 71 568 5333
Transplant Center Services
TCS phone
: +31 71 568 5330 (24/7)
Fax
: +31 71 711 3101
www.matchis.nl<http://www.matchis.nl/>
[Matchis Logo]<https://www.matchis.nl/>

[Matchis Instagram]<https://www.instagram.com/stichtingmatchis>    [Matchis Facebook] <https://facebook.com/stichtingmatchis/>     [Matchis LinkedIn] <https://www.matchis.nl/linkedin>     [Matchis Twitter] <https://twitter.com/matchisNL/>     [Matchis YouTube] <http://www.youtube.com/channel/UCZ31uzINIPlqaeTIm2OiSnw/videos>

**Comment by mbraakman** [comment]
> Hi, I've been using Haplomat for a while, but i get an error now i haven't gotten before.
> 
> I tried to run Haplomat for just DQB1 data, if I run g resolution or 4d it works. When selecting P or G I get a _'segmentation fault (core dumped)'_
> 
> any suggestions?
> 
> ```
>  _Hapl-o-Mat
>  Copyright (C) 2016 DKMS gGmbH
> ```
> 
> #########Initialization MA format #########Parameters I/O Input: Matchispopulation/DQA-DQB114042022.dat Output haplotypes: run/haplotypes.dat Output genotypes: run/genotypes.dat Output estimated haplotype frequencies: run/hfs.dat Output epsilon and log(L): run/epsilon.dat #########Parameters resolving genotypes Minimal frequency of genotypes: 1e-05 Loci with target allele resolutions: DQB1 : G Apply ambiguity filter: no #########Parameters EM algorithm Haplotype frequency initialization: perturbation Epsilon: 1e-06 Cut haplotype frequencies: 1e-06 Renormalize haplotype frequencies Zero: 1e-14 Seed: 1000
> 
> #########Data preprocessing Segmentation fault (core dumped)_

the problem seems to have returned? 
I've checked, no missing alleles and it only occurs when running DQB1/DPB1 on P or G group level.

**Comment by usolloch** [comment]
Hi,
thank you very much for your message. We were able to reproduce the error on our end and trace it back to a change in the format of the IMGT/HLA data to be downloaded. We are working on the fix and hope to provide it to you tomorrow.

**Comment by usolloch** [comment]
Hi Martijn,

we have merged a small patch into Hapl-o-Mat files this morning. The changes involve solely files BuildLargeG.py and BuildP.py in folder prepareData.
This should resolve your problems with DQB1 and DPB1 calculations. 

If you still encounter any problems, please do not hesitate to contact us. Your feedback is very appreciated.

Regards, Ute
