### ISSUE TITLE
N Error

### ISSUE THREAD

**Issue by iapaezg** [DKMS/Hapl-o-Mat#4]
Dear DKMS,

I have been working with some alleles code as XX:XX:XXG. I tried to run Hapl-o-Mat using "g" groups as part of my study. However, once I reviewed the result files I found that there was a bug: some alleles are coded with a "N" at the end of each code not "g" or only XX:XX. Have I done anything wrong?

Please help me :) my genes will thank you...

Kind regards,

**Comment by usolloch** [comment]
It is possible that some small g-groups comprise only one allele. These groups do not get a trailing 'g', but are named by their single allele name. If that allele is a null allele it has a trailing 'N'.
